name: Build and Release macOS Flutter App

on:
  push:
    tags:
      - 'v*.*.*' # Trigger the workflow only when a tag like v1.0.1 is pushed

env:
  FLUTTER_VERSION: "3.24.5"

jobs:
  build-macos:
    name: Build macOS App
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Install Flutter Dependencies
      run: flutter pub get

    - name: Enable macOS Support
      run: flutter config --enable-macos-desktop

    - name: Build macOS App
      run: flutter build macos --release

    - name: Create DMG Configuration File
      run: |
        mkdir -p dmg-config
        cat <<EOF > dmg-config/dmg-config.json
        {
          "title": "Flutter App",
          "icon": "assets/images/logo.png",
          "contents": [
            {
              "x": 448,
              "y": 344,
              "type": "link",
              "path": "/Applications"
            },
            {
              "x": 192,
              "y": 344,
              "type": "file",
              "path": "build/macos/Build/Products/Release/Flutter Build.app"
            }
          ],
          "icon-size": 128,
          "window": {
            "size": {
              "width": 640,
              "height": 480
            }
          }
        }
        EOF

    - name: Install create-dmg
      run: npm install --global create-dmg

    - name: Package DMG File
      run: |
        create-dmg --config dmg-config/dmg-config.json --overwrite .
        mv Flutter\ App*.dmg "flutter-build-macos-${GITHUB_REF_NAME}.dmg"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-dmg
        path: "flutter-build-macos-${GITHUB_REF_NAME}.dmg"

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "flutter-build-macos-${GITHUB_REF_NAME}.dmg"
        token: ${{ secrets.TOKEN }}
        tag: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        body: |
          This release includes the macOS build of the Flutter app.
          - Tag: ${{ github.ref_name }}
        draft: false
        prerelease: false