name: Build and Release Flutter App

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v1.1.0, etc.

env:
  FLUTTER_VERSION: "3.24.5"
  APP_NAME: "your-app-name"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev
        sudo apt-get install -y appimage-builder

    - name: Install Flutter Distributor
      run: flutter pub add flutter_distributor

    - name: Build Linux packages
      run: |
        flutter pub get
        flutter_distributor build --targets linux-deb,linux-appimage --platform linux

    - name: Upload Linux artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.deb
          dist/*.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Install Inno Setup
      run: choco install innosetup -y

    - name: Install Flutter Distributor
      run: flutter pub add flutter_distributor

    - name: Build Windows executable
      run: |
        flutter pub get
        flutter_distributor build --targets exe --platform windows

    - name: Upload Windows artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Install create-dmg
      run: brew install create-dmg

    - name: Install Flutter Distributor
      run: flutter pub add flutter_distributor

    - name: Build macOS DMG
      run: |
        flutter pub get
        flutter_distributor build --targets dmg --platform macos

    - name: Upload macOS artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}